FROM cassandra:latest

#WORKDIR /app 

# Copia los archivos necesarios 

# COPY schema.cql /app/etc/cassandra/schema.cql 

# COPY entrypoint.sh /app/entrypoint.sh 

# Otorga permisos de ejecución al script de entrada 

#RUN chmod +x /app/entrypoint.sh 

# Configura el script de entrada para ejecutar el comando CQL 
#ENTRYPOINT ["/app/entrypoint.sh"] 
CMD ["cassandra", "-f"]
