# Usa una imagen base de ZooKeeper
FROM bitnami/zookeeper:3.9.1

WORKDIR /app


# Copia el archivo de configuración de ZooKeeper
#COPY zookeeper.properties /opt/bitnami/zookeeper/conf/zookeeper.properties

#COPY zookeeper-server-start.sh /opt/bitnami/zookeeper/bin/zookeeper-server-start.sh

#COPY kafka-run-class.sh /opt/bitnami/zookeeper/bin/kafka-run-class.sh




# Expone el puerto en el que se ejecutará ZooKeeper (si es necesario)
EXPOSE 2181


# Comando para ejecutar ZooKeeper
#CMD ["/opt/bitnami/zookeeper/bin/zookeeper-server-start.sh", "/opt/bitnami/zookeeper/conf/zookeeper.properties"]
