version: '3'


networks:
  mynetwork:
    driver: bridge

services:

      
  mongo:
    image: mongo:6.0
    container_name: mongo-container
    hostname: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - .:/practica_creativa
    networks:
      - mynetwork

  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper-container
    hostname: zookeeper-container
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mynetwork

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "flight_delay_classification_request"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - mynetwork
    

  cassandra:
    image: cassandra-service
    container_name: cassandra-container
    hostname: cassandra-container
    ports:
      - "9042:9042"
    networks:
      - mynetwork

  flask:
    image: flask-web-service
    container_name: flask-container
    hostname: flask-container
    ports:
      - "5001:5001"
      - "9200:9200"
    depends_on:
      - mongo
      - cassandra
      - spark-master
      - spark-submit
    environment:
      - PROJECT_HOME=/app
    networks:
      - mynetwork


  spark-master:
    image: spark-service
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "9001:9001"
      - "8080:8080"
    depends_on:
      - kafka
      - mongo
      - cassandra
      - zookeeper
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-master"
    volumes:
      - .:/practica_creativa 
    networks:
      - mynetwork
      
      

  spark-worker-1:
    image: spark-service
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
      - kafka
      - mongo
      - cassandra
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-worker"
    volumes:
      - .:/practica_creativa
    networks:
      - mynetwork
      
      

  spark-worker-2:
    image: spark-service
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
      - kafka
      - mongo
      - cassandra
      - zookeeper
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "constraint:node==spark-master"
    volumes:
      - .:/practica_creativa
    networks:
      - mynetwork
      
      

  spark-submit:
    image: spark-service
    container_name: spark-submit
    hostname: spark-submit
    depends_on:
      - kafka
      - mongo
      - cassandra
      - zookeeper
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "KAFKA_BROKER=kafka-container:9092"
      - "constraint:node==spark-master"
    command: bash -c "sleep 180s; ./bin/spark-submit  --class es.upm.dit.ging.predictor.MakePrediction --master local[*] --packages com.datastax.spark:spark-cassandra-connector_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 /practica_creativa/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"
    volumes:
      - .:/practica_creativa
    networks:
      - mynetwork
      


