# Usa una imagen de Python como base
FROM python:3.10

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el código de la aplicación al contenedor
COPY resources/web/predict_flask.py .

# Copia el archivo de requisitos si existe
COPY requirements.txt . 

# Añade permisos de ejecución al archivo predict_flask.py
RUN chmod +x predict_flask.py

# Instala las dependencias, incluyendo Flask
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5001

# Define la variable de entorno FLASK_APP
ENV FLASK_APP=predict_flask.py

# Comando para ejecutar el archivo predict_flask.py
CMD ["python", "predict_flask.py"]

